---
- hosts: all
  become: yes


  tasks:
    - name: Installing Apache & PHP
      yum:
        name:
          - httpd
          - php
        state: installed

    - name: Enabling httpd service and start the service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Copying your php file in the /var/www/html
      copy:
        src: /home/ansadmin/index.php
        dest: /var/www/html/index.php
        force: yes

      notify:
          - restart httpd service

  handlers:
    - name: restart httpd service
      service:
        name: httpd
        state: restarted
